name: crystap
description: Tap the Crystal!

version: 1.1.0

dependencies:
  flutter:
    sdk: flutter
  flame:
    path: ../../../flame
  play_games:
    path: ../../../play_games

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter:
  uses-material-design: false

  assets:
   - assets/images/bag.png
   - assets/images/crystal.png
   - assets/audio/pickup.mp3

  fonts:
    - family: Stacked
      fonts:
        - asset: assets/fonts/Stacked.ttf
