name: crystap
description: Tap the Crystal!

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  flame:
    path: ../../../flame
  play_games:
    path: ../../../play_games

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
   - assets/images/bag.png
   - assets/images/crystal.png

  fonts:
    - family: Stacked
      fonts:
        - asset: assets/fonts/Stacked.ttf
