name: crystap
description: Tap the Crystal!

version: 1.8.0

dependencies:
  flutter:
    sdk: flutter
  flame: 0.9.5
  play_games: 0.2.0
  flutter_inapp_purchase: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter:
  uses-material-design: false

  assets:
    - assets/images/bag.png
    - assets/images/check.png
    - assets/images/coins.png
    - assets/images/crystal.png
    - assets/audio/pickup.mp3

  fonts:
    - family: Stacked
      fonts:
        - asset: assets/fonts/Stacked.ttf
